main: de.raidcraft.mobs.MobsPlugin
name: RCMobs
version: ${project.version}#${build.number}
description: API for creating custom mobs and boss fights.
author: Silthus
website: http://www.raid-craft.de
depend: [RaidCraft-API]
softdepend: [RCSkills]
database: true